// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using energy.Data;

#nullable disable

namespace energy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240323234407_AddConsumptionPerMonth")]
    partial class AddConsumptionPerMonth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("energy.Models.ConsumptionPerDay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KWHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ConsumptionPerDay");
                });

            modelBuilder.Entity("energy.Models.ConsumptionPerMonth", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KWHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ConsumptionPerMonth");
                });

            modelBuilder.Entity("energy.Models.CurrentVoltKWHourPerDay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KWHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CurrentVoltKWHourPerDay");
                });

            modelBuilder.Entity("energy.Models.CurrentVoltKWHourPerHour", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KWHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CurrentVoltKWHourPerHour");
                });

            modelBuilder.Entity("energy.Models.CurrentVoltKWHourPerMonth", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KWHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CurrentVoltKWHourPerMonth");
                });

            modelBuilder.Entity("energy.Models.CurrentVoltMinutes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CurrentVoltMinutes");
                });

            modelBuilder.Entity("energy.Models.CurrentVoltSecond", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("CurrentVoltSecond");
                });

            modelBuilder.Entity("energy.Models.Device1", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KWHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Device1");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DeviceCurrent = 21,
                            DeviceInfo = "Device1",
                            DeviceName = "D-1",
                            KWHour = 4,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(70),
                            volt = 42
                        },
                        new
                        {
                            id = 2,
                            DeviceCurrent = 31,
                            DeviceInfo = "Device1",
                            DeviceName = "D-1",
                            KWHour = 8,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(73),
                            volt = 45
                        },
                        new
                        {
                            id = 3,
                            DeviceCurrent = 29,
                            DeviceInfo = "Device1",
                            DeviceName = "D-1",
                            KWHour = 12,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(75),
                            volt = 47
                        },
                        new
                        {
                            id = 4,
                            DeviceCurrent = 76,
                            DeviceInfo = "Device1",
                            DeviceName = "D-1",
                            KWHour = 22,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(76),
                            volt = 52
                        },
                        new
                        {
                            id = 5,
                            DeviceCurrent = 51,
                            DeviceInfo = "Device1",
                            DeviceName = "D-1",
                            KWHour = 7,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(78),
                            volt = 21
                        });
                });

            modelBuilder.Entity("energy.Models.Device2", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DeviceCurrent")
                        .HasColumnType("int");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("KWHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("volt")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Device2");

                    b.HasData(
                        new
                        {
                            id = 1,
                            DeviceCurrent = 26,
                            DeviceInfo = "Device2",
                            DeviceName = "D-2",
                            KWHour = 32,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(247),
                            volt = 62
                        },
                        new
                        {
                            id = 2,
                            DeviceCurrent = 35,
                            DeviceInfo = "Device2",
                            DeviceName = "D-2",
                            KWHour = 5,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(249),
                            volt = 15
                        },
                        new
                        {
                            id = 3,
                            DeviceCurrent = 29,
                            DeviceInfo = "Device2",
                            DeviceName = "D-2",
                            KWHour = 12,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(251),
                            volt = 47
                        },
                        new
                        {
                            id = 4,
                            DeviceCurrent = 76,
                            DeviceInfo = "Device2",
                            DeviceName = "D-2",
                            KWHour = 22,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(253),
                            volt = 52
                        },
                        new
                        {
                            id = 5,
                            DeviceCurrent = 11,
                            DeviceInfo = "Device2",
                            DeviceName = "D-2",
                            KWHour = 12,
                            Time = new DateTime(2024, 3, 23, 23, 44, 5, 704, DateTimeKind.Utc).AddTicks(254),
                            volt = 51
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
